baseURL = "https://xxkizashi.github.io/blank-space/"
languageCode = "ja-jp"
title = "Blank Space"
theme = "Mainroad"
paginate = 5
hasCJKLanguage = true
publishDir = "docs"
canonifyurls = true
summaryLength = 120
googleAnalytics = ""

[Params]
  description = "xxkizashi's personal blog"
  twitter_cards = true
  readmore = true
  pager = true
  mathjax = true
  googleFontsLink = "https://fonts.googleapis.com/css2?family=Ubuntu:wght@700"
  post_navigation = true
  postSections = ["posts"]
  post_meta = ["date", "categories"] # Order of post meta information
  highlightColor = "#33709d"
  customCSS = ["css/custom-font.css"] # Include custom CSS files

[[Menus.main]]
  Name = "Home"
  URL = "/"
  weight = 1

[[Menus.main]]
  Name = "FSAE"
  URL = "https://xxkizashi.github.io/FSAE_TO_WIN/"
  weight = 5

[Params.logo]
  subtitle = "You only live once. Let's do it."

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  widgets = ["recent", "categories", "taglist", "social", "search"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget

[Params.widgets.social]
  twitter = "xxKFZ1S"
  github = "xxkizashi"

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true