baseURL = "https://xxkizashi.github.io/blank-space/"
languageCode = "ja-jp"
title = "Blank Space"
theme = "Mainroad"
paginate = 10
hasCJKLanguage = true
publishDir = "docs"
canonifyurls = true
summaryLength = 120
googleAnalytics = ""

[Params]
  description = "xxkizashi's personal blog about everything"
  twitter_cards = false
  readmore = true
  pager = true
  mathjax = true
  post_navigation = true
  postSections = ["posts"]
  post_meta = ["date", "categories"] # Order of post meta information
  highlightColor = "#2189c8"
  customCSS = ["css/custom-font.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

[[Menus.main]]
  Name = "Home"
  URL = "/"
  weight = 1

[[Menus.main]]
  Name = "FSAE"
  URL = "https://xxkizashi.github.io/FSAE_TO_WIN/"
  weight = 5


[Params.logo]
  subtitle = "No Attach No Chance"

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  widgets = ["recent", "categories", "taglist", "social"]

[Params.widgets.social]
  twitter = "xxKFZ1S"
  github = "xxkizashi"